import type { Listing } from '../types';

// Mock data for listings
export const mockListings: Listing[] = [
  {
    id: '1',
    name: 'Modern Loft with Skyline View',
    type: 'Entire apartment',
    price: 125,
    image: 'https://images.pexels.com/photos/1918291/pexels-photo-1918291.jpeg?auto=compress&cs=tinysrgb&w=800',
    rating: 4.93,
    reviews: 124,
    beds: 2,
    baths: 1,
    lat: 48.857,
    lng: 2.354,
    distanceMinutes: 8,
    travelMode: 'walk',
    amenities: ['wifi', 'kitchen', 'washer', 'dryer', 'tv', 'aircon'],
    tags: ['Superhost', 'Great location', 'Self check-in'],
    host: {
      name: 'Marie',
      isSuperhost: true,
    },
  },
  {
    id: '2',
    name: 'Charming Studio near Parks',
    type: 'Studio',
    price: 95,
    image: 'https://images.pexels.com/photos/1571460/pexels-photo-1571460.jpeg?auto=compress&cs=tinysrgb&w=800',
    rating: 4.87,
    reviews: 93,
    beds: 1,
    baths: 1,
    lat: 48.859,
    lng: 2.349,
    distanceMinutes: 12,
    travelMode: 'walk',
    amenities: ['wifi', 'kitchen', 'tv'],
    tags: ['Best value', 'Quick responses', 'Thoughtfully designed'],
    host: {
      name: 'Jean',
      isSuperhost: false,
    },
  },
  {
    id: '3',
    name: 'Luxury Penthouse with Terrace',
    type: 'Entire apartment',
    price: 310,
    image: 'https://images.pexels.com/photos/1643384/pexels-photo-1643384.jpeg?auto=compress&cs=tinysrgb&w=800',
    rating: 4.98,
    reviews: 57,
    beds: 3,
    baths: 2,
    lat: 48.854,
    lng: 2.356,
    distanceMinutes: 18,
    travelMode: 'walk',
    amenities: ['wifi', 'kitchen', 'washer', 'dryer', 'tv', 'aircon', 'pool', 'gym'],
    tags: ['Superhost', 'Exceptional hospitality', 'Luxurious amenities'],
    host: {
      name: 'Philippe',
      isSuperhost: true,
    },
  },
  {
    id: '4',
    name: 'Cozy Apartment with River View',
    type: 'Entire apartment',
    price: 175,
    image: 'https://images.pexels.com/photos/1457842/pexels-photo-1457842.jpeg?auto=compress&cs=tinysrgb&w=800',
    rating: 4.85,
    reviews: 112,
    beds: 2,
    baths: 1,
    lat: 48.853,
    lng: 2.348,
    distanceMinutes: 25,
    travelMode: 'transit',
    amenities: ['wifi', 'kitchen', 'washer', 'tv', 'aircon'],
    tags: ['Great view', 'Well-equipped kitchen', 'Public transit'],
    host: {
      name: 'Sophie',
      isSuperhost: false,
    },
  },
  {
    id: '5',
    name: 'Historical Building Apartment',
    type: 'Entire apartment',
    price: 145,
    image: 'https://images.pexels.com/photos/2079246/pexels-photo-2079246.jpeg?auto=compress&cs=tinysrgb&w=800',
    rating: 4.91,
    reviews: 78,
    beds: 1,
    baths: 1,
    lat: 48.862,
    lng: 2.35,
    distanceMinutes: 15,
    travelMode: 'walk',
    amenities: ['wifi', 'kitchen', 'washer', 'tv'],
    tags: ['Historical building', 'Great location', 'Highly rated host'],
    host: {
      name: 'Claude',
      isSuperhost: true,
    },
  },
  {
    id: '6',
    name: 'Bright Studio with Balcony',
    type: 'Studio',
    price: 85,
    image: 'https://images.pexels.com/photos/2462015/pexels-photo-2462015.jpeg?auto=compress&cs=tinysrgb&w=800',
    rating: 4.82,
    reviews: 65,
    beds: 1,
    baths: 1,
    lat: 48.858,
    lng: 2.347,
    distanceMinutes: 10,
    travelMode: 'walk',
    amenities: ['wifi', 'kitchen', 'tv'],
    tags: ['Budget friendly', 'Central location', 'Outdoor space'],
    host: {
      name: 'Emilie',
      isSuperhost: false,
    },
  },
  {
    id: '7',
    name: 'Designer Apartment with Garden',
    type: 'Entire apartment',
    price: 195,
    image: 'https://images.pexels.com/photos/1642125/pexels-photo-1642125.jpeg?auto=compress&cs=tinysrgb&w=800',
    rating: 4.95,
    reviews: 43,
    beds: 2,
    baths: 1,
    lat: 48.855,
    lng: 2.36,
    distanceMinutes: 30,
    travelMode: 'transit',
    amenities: ['wifi', 'kitchen', 'washer', 'dryer', 'tv', 'aircon', 'garden'],
    tags: ['Superhost', 'Designer interior', 'Outdoor space'],
    host: {
      name: 'Antoine',
      isSuperhost: true,
    },
  },
];

// Mock data for Points of Interest
export const mockPOIs = [
  {
    name: 'Eiffel Tower',
    city: 'Paris',
    lat: 48.8584,
    lng: 2.2945,
  },
  {
    name: 'Louvre Museum',
    city: 'Paris',
    lat: 48.8606,
    lng: 2.3376,
  },
  {
    name: 'Notre-Dame Cathedral',
    city: 'Paris',
    lat: 48.8530,
    lng: 2.3499,
  },
  {
    name: 'Times Square',
    city: 'New York',
    lat: 40.7580,
    lng: -73.9855,
  },
  {
    name: 'Central Park',
    city: 'New York',
    lat: 40.7829,
    lng: -73.9654,
  },
];

// Mock amenity tags
export const amenityTags = [
  { id: 'wifi', label: '📶 WiFi', description: 'Fast WiFi available' },
  { id: 'kitchen', label: '🍳 Kitchen', description: 'Full kitchen' },
  { id: 'washer', label: '🧺 Washer', description: 'In-unit washer' },
  { id: 'dryer', label: '👕 Dryer', description: 'In-unit dryer' },
  { id: 'tv', label: '📺 TV', description: 'Television with streaming' },
  { id: 'aircon', label: '❄️ Air conditioning', description: 'Air conditioning available' },
  { id: 'pool', label: '🏊 Pool', description: 'Access to pool' },
  { id: 'gym', label: '🏋️ Gym', description: 'Access to fitness center' },
  { id: 'garden', label: '🌿 Garden', description: 'Private or shared garden' },
  { id: 'parking', label: '🅿️ Parking', description: 'Free parking on premises' },
];

// Mock transport types
export const transportTypes = [
  { id: 'walk', label: '🚶 Walking', description: 'Walking distance' },
  { id: 'transit', label: '🚇 Transit', description: 'Public transportation available' },
  { id: 'drive', label: '🚗 Drive', description: 'Short drive' },
];